spring:
  application:
    name: customer-service
  jackson:
    serialization:
      indent-output: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"